### ISSUE TITLE
Add field for sorting

### ISSUE THREAD

**Issue by pqab** [kan01234/jobad-reader#2]
**Is your feature request related to a problem? Please describe.**
Add sortBy and sortOrder field for table sorting.

**Describe the solution you'd like**
Add query params for sorting in /api/v1/list
e.g.
sort by title desc -> /api/v1/list?sortBy=title&sortOrder=desc
sort by title asc -> /api/v1/list?sortBy=title
sortOrder can be Optional and default is asc

`Remove unnecessary multiple sorting`
<del>**Describe alternatives you've considered**
Add query for multiple fields and orders sorting
e.g.
sort by title desc, date asc -> /api/v1/list?sort=title:desc,date,asc
or change to POST request</del>

**Comment by kan01234** [comment]
pls check this [commit](https://github.com/dotterbear/service-jobad-reader/commit/a56414c7f3f0dd4592a8f38313f8c95eccd7e2e6), thanks

**Comment by pqab** [comment]
**Suggestion**

Sorted by original postedDate with timestamp instead of create date

**Comment by kan01234** [comment]
fixed in this [commit](https://github.com/dotterbear/service-jobad-reader/commit/1d9217b3618ce680aa2cfb6b305073835362b844), please try, thanks.

**Comment by kan01234** [comment]
inactive issue, close it.
