### ISSUE TITLE
Add different search query for filtering

### ISSUE THREAD

**Issue by pqab** [kan01234/jobad-reader#3]
**Is your feature request related to a problem? Please describe.**
Add different search query for filtering

**Describe the solution you'd like**
Add query params to /api/v1/list for searching
e.g.
search by title -> /api/v1/list?title=t

**Comment by kan01234** [comment]
now support using
/list?query=xxx -> to perform in text search in title and job details, also support sort by the score in ascending order only. thanks.

**Comment by kan01234** [comment]
now support using
/list?query=xxx&company-name=xxx -> to perform and case searching, will support more fields later.
Thanks.

**Comment by pqab** [comment]
> now support using
> /list?query=xxx&company-name=xxx -> to perform and case searching, will support more fields later.
> Thanks.

Ok
